const reactTemplate = {
  "src": {
    "type": "directory",
    "children": {
      "App.jsx": {
        "type": "file",
        "content": `import React, { useState } from 'react';\nimport './App.css';\n\nfunction App() {\n  const [count, setCount] = useState(0);\n\n  return (\n    <div className="App">\n      <header className="App-header">\n        <h1>Hello React!</h1>\n        <p>Edit src/App.jsx and save to reload.</p>\n        <button onClick={() => setCount(count + 1)}>\n          Count is: {count}\n        </button>\n      </header>\n    </div>\n  );\n}\n\nexport default App;\n`
      },
      "App.css": {
        "type": "file",
        "content": `.App {\n  text-align: center;\n  font-family: sans-serif;\n}\n\n.App-header {\n  background-color: #282c34;\n  min-height: 100vh;\n  display: flex;\n  flex-direction: column;\n  align-items: center;\n  justify-content: center;\n  font-size: calc(10px + 2vmin);\n  color: white;\n}\n\nbutton {\n  margin-top: 20px;\n  padding: 10px 20px;\n  font-size: 16px;\n  cursor: pointer;\n  background: #61dafb;\n  border: none;\n  border-radius: 4px;\n  color: #282c34;\n  font-weight: bold;\n}`
      },
      "main.jsx": {
        "type": "file",
        "content": `import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport App from './App';\n\nconst root = ReactDOM.createRoot(document.getElementById('root'));\nroot.render(\n  <React.StrictMode>\n    <App />\n  </React.StrictMode>\n);\n`
      }
    }
  },
  "package.json": {
    "type": "file",
    "content": `{\n  "name": "react-starter",\n  "version": "1.0.0",\n  "private": true,\n  "scripts": {\n    "dev": "vite",\n    "build": "vite build"\n  },\n  "dependencies": {\n    "react": "^18.2.0",\n    "react-dom": "^18.2.0"\n  },\n  "devDependencies": {\n    "vite": "^5.0.0",\n    "@vitejs/plugin-react": "^4.2.0"\n  }\n}`
  },
  "index.html": {
    "type": "file",
    "content": `<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8" />\n    <title>React App</title>\n  </head>\n  <body>\n    <noscript>You need to enable JavaScript to run this app.</noscript>\n    <div id="root"></div>\n    <script type="module" src="/src/main.jsx"></script>\n  </body>\n</html>`
  },
  "vite.config.js": {
    "type": "file",
    "content": `import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\n\nexport default defineConfig({\n  plugins: [react()],\n});\n`
  }
};

const defaultTemplate = {
  "index.js": {
    "type": "file",
    "content": `console.log('Hello World!');\n`
  },
  "README.md": {
    "type": "file",
    "content": `# My Project\n\nWelcome to your new project!\n`
  }
};

const nextjsTemplate = {
  "app": {
    "type": "directory",
    "children": {
      "page.tsx": {
        "type": "file",
        "content": `export default function Home() {\n  return (\n    <main className="flex min-h-screen flex-col items-center justify-between p-24">\n      <h1>Welcome to Next.js!</h1>\n    </main>\n  )\n}\n`
      },
      "layout.tsx": {
        "type": "file",
        "content": `import './globals.css'\n\nexport const metadata = {\n  title: 'Next.js App',\n  description: 'Generated by create next app',\n}\n\nexport default function RootLayout({\n  children,\n}: {\n  children: React.ReactNode\n}) {\n  return (\n    <html lang="en">\n      <body>{children}</body>\n    </html>\n  )\n}\n`
      },
      "globals.css": {
        "type": "file",
        "content": `body {\n  font-family: sans-serif;\n  background: #0f172a;\n  color: white;\n}\n`
      }
    }
  },
  "package.json": {
    "type": "file",
    "content": `{\n  "name": "nextjs-starter",\n  "version": "1.0.0",\n  "private": true,\n  "scripts": {\n    "dev": "next dev",\n    "build": "next build",\n    "start": "next start"\n  },\n  "dependencies": {\n    "next": "latest",\n    "react": "latest",\n    "react-dom": "latest"\n  }\n}`
  }
};

const expressTemplate = {
  "src": {
    "type": "directory",
    "children": {
      "index.js": {
        "type": "file",
        "content": `const express = require('express');\nconst app = express();\nconst port = 3000;\n\napp.get('/', (req, res) => {\n  res.send('Hello World from Express!');\n});\n\napp.listen(port, () => {\n  console.log(\`Example app listening on port \${port}\`);\n});\n`
      }
    }
  },
  "package.json": {
    "type": "file",
    "content": `{\n  "name": "express-starter",\n  "version": "1.0.0",\n  "main": "src/index.js",\n  "scripts": {\n    "start": "node src/index.js",\n    "dev": "node src/index.js"\n  },\n  "dependencies": {\n    "express": "^4.18.2"\n  }\n}`
  }
};

const vueTemplate = {
  "src": {
    "type": "directory",
    "children": {
      "App.vue": {
        "type": "file",
        "content": `<script setup>\nimport { ref } from 'vue'\n\nconst count = ref(0)\n</script>\n\n<template>\n  <h1>Hello Vue!</h1>\n  <button @click="count++">Count is: {{ count }}</button>\n</template>\n\n<style scoped>\nh1 {\n  color: #42b883;\n}\n</style>\n`
      },
      "main.js": {
        "type": "file",
        "content": `import { createApp } from 'vue'\nimport App from './App.vue'\n\ncreateApp(App).mount('#app')\n`
      }
    }
  },
  "package.json": {
    "type": "file",
    "content": `{\n  "name": "vue-starter",\n  "version": "1.0.0",\n  "private": true,\n  "scripts": {\n    "dev": "vite",\n    "build": "vite build"\n  },\n  "dependencies": {\n    "vue": "^3.3.4"\n  },\n  "devDependencies": {\n    "vite": "^5.0.0",\n    "@vitejs/plugin-vue": "^4.5.0"\n  }\n}`
  },
  "index.html": {
    "type": "file",
    "content": `<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8">\n    <title>Vue App</title>\n  </head>\n  <body>\n    <div id="app"></div>\n    <script type="module" src="/src/main.js"></script>\n  </body>\n</html>`
  },
  "vite.config.js": {
    "type": "file",
    "content": `import { defineConfig } from 'vite';\nimport vue from '@vitejs/plugin-vue';\n\nexport default defineConfig({\n  plugins: [vue()],\n});\n`
  }
};

const honoTemplate = {
  "src": {
    "type": "directory",
    "children": {
      "index.ts": {
        "type": "file",
        "content": `import { serve } from '@hono/node-server'\nimport { Hono } from 'hono'\n\nconst app = new Hono()\n\napp.get('/', (c) => {\n  return c.text('Hello Hono!')\n})\n\nserve({ fetch: app.fetch, port: 3000 }, (info) => {\n  console.log(\`Server is running on http://localhost:\${info.port}\`)\n})\n`
      }
    }
  },
  "package.json": {
    "type": "file",
    "content": `{\n  "name": "hono-starter",\n  "version": "1.0.0",\n  "scripts": {\n    "dev": "tsx src/index.ts",\n    "start": "tsx src/index.ts"\n  },\n  "dependencies": {\n    "hono": "^3.12.0",\n    "@hono/node-server": "^1.3.0"\n  },\n  "devDependencies": {\n    "tsx": "^4.7.0"\n  }\n}`
  }
};

const angularTemplate = {
  "src": {
    "type": "directory",
    "children": {
      "app": {
        "type": "directory",
        "children": {
          "app.component.ts": {
            "type": "file",
            "content": `import { Component } from '@angular/core';\n\n@Component({\n  selector: 'app-root',\n  template: \`\n    <h1>Hello Angular!</h1>\n    <p>Welcome to your new app.</p>\n  \`\n})\nexport class AppComponent {\n  title = 'angular-starter';\n}\n`
          }
        }
      },
      "main.ts": {
        "type": "file",
        "content": `import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';\nimport { AppModule } from './app/app.module';\n\nplatformBrowserDynamic().bootstrapModule(AppModule)\n  .catch(err => console.error(err));\n`
      }
    }
  },
  "package.json": {
    "type": "file",
    "content": `{\n  "name": "angular-starter",\n  "version": "1.0.0",\n  "scripts": {\n    "start": "ng serve",\n    "dev": "ng serve"\n  },\n  "dependencies": {\n    "@angular/core": "^16.0.0"\n  }\n}`
  }
};

export const getTemplateFiles = (templateName) => {
  switch (templateName) {
    case 'react':
      return reactTemplate;
    case 'next.js':
      return nextjsTemplate;
    case 'express':
      return expressTemplate;
    case 'vue':
      return vueTemplate;
    case 'hono':
      return honoTemplate;
    case 'angular':
      return angularTemplate;
    default:
      return defaultTemplate;
  }
};
